apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-application
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sync-application
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: sync-application
    targetRevision: {{ .Values.spec.source.targetRevision }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
