apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Release.Namespace }}-test
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: sync-application
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values-test.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
